Store:
  Driver: mysql
  Host: HOST
  Port: PORT
  User: root
  Password: PWD
  MaxOpenConns: 2
  MaxIdleConns: 1
  ConnMaxLifeTime: 3
RequestTimeout: 10
TimeoutToFail: 10
RetryInterval: 10
RetryLimit: 0
TransCronInterval: 3
LogLevel: 'debug'
