Store:
  Driver: mysql
  Host: HOST
  Port: PORT
  User: root
  Password: PWD
  MaxOpenConns: 2
  MaxIdleConns: 1
  ConnMaxLifeTime: 3
  RequestTimeout: 1800
  TimeoutToFail: 1800
  RetryInterval: 1800
  TransCronInterval: 1800
