Store:
  Driver: mysql
  Host: HOST
  Port: PORT
  User: root
  Password: PWD
  MaxOpenConns: 2
  MaxIdleConns: 1
  ConnMaxLifeTime: 3
  RequestTimeout: 18000000
  TimeoutToFail: 18000000
  RetryInterval: 18000000
  TransCronInterval: 1800000
